32

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -27,7 +27,13 @@ jobs:
           
       - name: Start EMR cluster
         run: |
-          aws emr start-cluster --MyEMRCluster MyEMRCluster
+          cluster_info=$(aws emr describe-clusters --query 'Clusters[?Name==`MyEMRCluster`].[Id]' --output text)
+
+          if [ -z "$cluster_info" ]; then
+              echo "Error: Cluster ID not found."
+          exit 1
+          fi
+          aws emr start-clusters --cluster-ids "$cluster_info"
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
